services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: sh -c "uvicorn main:app --reload --port=8000 --host=0.0.0.0"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - internal
    depends_on:
      postgre:
        condition: service_healthy

  postgre:
    image: postgres:16
    volumes:

networks:
  internal:
    driver: bridge
